<div id="colorizedDiv" data-mage-init='{"colorizer": {"color": "red"}}'>This should be red</div>
<div class="colorized-divs">This should be green</div>
<div class="colorized-divs">This should be green</div>
<div class="colorized-divs">This should be green</div>
<div class="colorized-divs-jq">This should be purple</div>
<div class="colorized-divs-jq">This should be purple</div>
<div class="colorized-divs-jq">This should be purple</div>
<script type="text/x-magento-init">
{
    ".colorized-divs": {
        "colorizer": {"color": "green"}
    }
}
</script>
<script>
   require(['jquery', 'colorizer'], function($) {
        $('.colorized-divs-jq').colorizer({
            color: 'purple',
            props: {
                'background-color': true,
                'color': false
            }
        });
   });
</script>
<style>
    .colorized-divs, #colorizedDiv, .colorized-divs-jq {
        border: 1px solid black;
    }
</style>